### PR TITLE
Remove calls to test APIs unavailable in jdk11u

### PR DESCRIPTION
**Pull request by swesonga**
Some of the usage of the OutputAnalyzer in the TestAvailableProcessors class depends on APIs that are not in the jdk11u OutputAnalyzer. This PR fixes these compilation errors in jdk11u, similar to the jdk17u fix in https://github.com/microsoft/openjdk-jdk17u/pull/30

The backport used the jdk21u APIs introduced in https://github.com/openjdk/jdk21u/commit/262cacb2385af4e0e2ee3a4e1f763b68e3101f28#diff-13897cfb2b23f2a1424c9874bdb40f563b56cd01d2b560ace927fe240d15a5a9 and should have used the previous OutputAnalyzer.
The backport also shouldn't have the fix for https://bugs.openjdk.org/browse/JDK-8315097

The difference between the jdk17u fix in https://github.com/microsoft/openjdk-jdk17u/pull/30 and this change is the extra commit https://github.com/microsoft/openjdk-jdk11u/commit/2f0a8ac991ed239050f535f8c62fcfc229dd972f required in jdk11u to get the test to run (otherwise it will not be selected to run).

### CODE REVIEW

**Review by brianjstafford — APPROVED** [review]
LGTM
